version: '3'

volumes:
    postgres_data:

services:
  nginx:
    container_name: 'nginx'
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - server

  server:
    container_name: 'server'
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/server"
    expose:
      - ${APP_PORT}
    volumes:
      - ./server/:/server/
    environment:
      - APP_PORT=${APP_PORT}
    command: make run
