version: '3'

volumes:
    postgres_data:

services:
  nginx:
    container_name: 'nginx'
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - server

  postgres:
    container_name: 'postgres'
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: postgres -p ${POSTGRES_PORT}

  server:
    container_name: 'server'
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/server"
    expose:
      - ${APP_PORT}
    volumes:
      - ./server/:/server/
    environment:
      - APP_PORT=${APP_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
    command: make run
